* Introducción a la infraestructura virtual: concepto y soporte físico
** Ejercicio 1
*** Descripción
Consultar en el catálogo de alguna tienda de informática el precio de
un ordenador tipo servidor y calcular su coste de amortización a
cuatro y siete años. Consultar [[https://infoautonomos.eleconomista.es/consultas-a-la-comunidad/988/][este artículo en Infoautónomos sobre el
tema]].

*** Solución
Se ha seleccionado el siguiente servidor: [[https://www.bargainhardware.co.uk/hp-dl380-g9-1u-12-lff-hs-configure-to-order][HP Proliant DL380]], sin
ningún tipo de configuración adicional ya que no es relevante para el
ejercicio.

Su coste es de *1263,60 Euros* impuestos incluidos, por lo tanto para
su amortización en cuatro y siete años suponiendo que se compra hoy
día 28 de Septiembre sería la siguiente:

**** Cuatro años
- *Precio sin impuestos*: 1263.60 / 1.21 = *1043.98*

|  Año | % amortización | Cantidad amortización | Comentario                                 |
|------+----------------+-----------------------+--------------------------------------------|
| 2019 |           8.33 |                 86.96 | 8.33% amortización comprando en Septiembre |
| 2020 |             25 |                   261 |                                            |
| 2021 |             25 |                   261 |                                            |
| 2022 |             25 |                   261 |                                            |
| 2023 |          16.67 |                   174 |                                            |

**** Siete años
- *Precio sin impuestos*: 1263.60 / 1.21 = *1043.98*

|  Año | % amortización | Cantidad amortización | Comentario                                 |
|------+----------------+-----------------------+--------------------------------------------|
| 2019 |           8.33 |                 86.96 | 8.33% amortización comprando en Septiembre |
| 2020 |           13.1 |                136.76 |                                            |
| 2021 |           13.1 |                136.76 |                                            |
| 2022 |           13.1 |                136.76 |                                            |
| 2023 |           13.1 |                136.76 |                                            |
| 2024 |           13.1 |                136.76 |                                            |
| 2025 |           13.1 |                136.76 |                                            |
| 2026 |           13.1 |                136.76 |                                            |

** Ejercicio 2

*** Descripción
Usando las tablas de precios de servicios de alojamiento en Internet
"clásicos", es decir, que ofrezcan Virtual Private Servers o
servidores físicos, y de proveedores de servicios en la nube, comparar
el coste durante un año de un ordenador con un procesador estándar
(escogerlo de forma que sea el mismo tipo de procesador en los dos
vendedores) y con el resto de las características similares (tamaño de
disco duro equivalente a transferencia de disco duro) en el caso de
que la infraestructura comprada se usa solo el 1% o el 10% del tiempo.

*** Solución
Se han seleccionado los proveedores: [[https://www.linode.com][Linode]] y [[https://www.hetzner.com/cloud?][Hetzner]], en
la siguiente tabla se muestra la relación de coste por tiempo de uso.

| Proveedor | VPS        | Coste Anual             | Uso del 1% | Uso del 10% |
|-----------+------------+-------------------------+------------+-------------|
| Linode    | Linode 4GB | 20 x 12 = 240 $         | 2.4 $      | 24 $        |
| Hetzner   | CX21       | 5.93 x 12 = 71.16 Euros | 0.71 Euros | 7.1 Euros   |


- *Linode 4GB*: 2 VCPU, 4GB RAM, 80 GB SSD Storage, 4 TB monthly
  transfer.
- *CX21*: 2 VCPU, 4GB RAM, 40 GB SSD Storage, 20 TB monthly transfer.

** Ejercicio 3
*** Descripción
En general, cualquier ordenador con menos de 5 o 6 años tendrá estos
flags. ¿Qué modelo de procesador es? ¿Qué aparece como salida de esa
orden? Si usas una máquina virtual, ¿qué resultado da? ¿Y en una
Raspberry Pi o, si tienes acceso, [[https://stackoverflow.com/questions/26239956/how-to-get-specific-information-of-an-android-device-from-proc-cpuinfo-file][el procesador móvil]].

*** Solución
- El procesador de mi portátil es un *Intel(R) Core(TM) i7-8750H*
  #+begin_src bash
    $ lscpu
    Architecture:                    x86_64
    CPU op-mode(s):                  32-bit, 64-bit
    Byte Order:                      Little Endian
    Address sizes:                   39 bits physical, 48 bits virtual
    CPU(s):                          12
    On-line CPU(s) list:             0-11
    Thread(s) per core:              2
    Core(s) per socket:              6
    Socket(s):                       1
    NUMA node(s):                    1
    Vendor ID:                       GenuineIntel
    CPU family:                      6
    Model:                           158
    Model name:                      Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Stepping:                        10
    CPU MHz:                         1347.282
    CPU max MHz:                     4100.0000
    CPU min MHz:                     800.0000
    BogoMIPS:                        4401.32
    Virtualization:                  VT-x
    L1d cache:                       192 KiB
    L1i cache:                       192 KiB
    L2 cache:                        1.5 MiB
    L3 cache:                        9 MiB
    NUMA node0 CPU(s):               0-11
    Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
    Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
    Vulnerability Meltdown:          Mitigation; PTI
    Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
    Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
    Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
    Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good no
                                     pl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rd
                                     rand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx
                                      smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
  #+end_src

- La salida de la comprobación de virtualización a nivel de hardware
  es:

  #+begin_src bash
    $ egrep '^flags.*(vmx|svm)' /proc/cpuinfo
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
  #+end_src

- En una máquina virtual:
  #+begin_src bash
    $ egrep '^flags.*(vmx|svm)' /proc/cpuinfo
  #+end_src

- Al no tener Raspberry PI a mano he decidido probar en un
  decodificador de satélite:
  #+begin_src bash
    root@vuzero:~# cat /proc/cpuinfo
    system type		: BCM7362A0 STB platform
    machine			: Unknown
    processor		: 0
    cpu model		: Broadcom BMIPS4380 V6.5  FPU V0.1
    BogoMIPS		: 749.56
    cpu MHz			: 751.523
    wait instruction	: yes
    microsecond timers	: yes
    tlb_entries		: 32
    extra interrupt vector	: yes
    hardware watchpoint	: no
    isa			: mips1 mips2 mips32r1
    ASEs implemented	: mips16
    shadow register sets	: 1
    kscratch registers	: 0
    core			: 0
    VCED exceptions		: not available
    VCEI exceptions		: not available

    processor		: 1
    cpu model		: Broadcom BMIPS4380 V6.5  FPU V0.1
    BogoMIPS		: 753.66
    cpu MHz			: 751.523
    wait instruction	: yes
    microsecond timers	: yes
    tlb_entries		: 32
    extra interrupt vector	: yes
    hardware watchpoint	: no
    isa			: mips1 mips2 mips32r1
    ASEs implemented	: mips16
    shadow register sets	: 1
    kscratch registers	: 0
    core			: 0
    VCED exceptions		: not available
    VCEI exceptions		: not available

    root@vuzero:~# egrep '^flags.*(vmx|svm)' /proc/cpuinfo
    root@vuzero:~#
  #+end_src

** Ejercicio 4
*** Descripción
1. Comprobar si el núcleo instalado en tu ordenador contiene este
   módulo del kernel usando la orden ~kvm-ok~. Alternativamente (o
   además), usar ~lscpu~ como se indica arriba.
2. Instalar un hipervisor para gestionar máquinas virtuales, que más
   adelante se podrá usar en pruebas y ejercicios.
*** Solución
1. El tipo de virtualización de mi portátil es: *VT-x*
   #+begin_src bash
     $ LC_ALL=C lscpu | grep Virtualization
     Virtualization:                  VT-x
     $ lsmod | grep kvm
     kvm_intel             311296  0
     kvm                   778240  1 kvm_intel
     irqbypass              16384  1 kvm
   #+end_src
2. Ya tenía instalado el hipervisor QEMU siguiendo la documentación
   oficial para Arch: [[https://wiki.archlinux.org/index.php/QEMU][aquí]].

** Ejercicio 5
*** Descripción
Darse de alta en servicios de nube usando ofertas gratuitas o cupones
que pueda proporcionar el profesor.
*** Solución
Me he dado de alta en [[https://www.oracle.com/corporate/pressrelease/oow19-oracle-free-tier-091619.html][Oracle cloud]] utilizando el free tier.
** Ejercicio 6
*** Descripción
Darse de alta en una web que permita hacer pruebas con alguno de los
sistemas de gestión de nube anteriores.
*** Solución
